org: dabolus
app: ${env:SERVICE_NAME}
service: ${env:SERVICE_NAME}
frameworkVersion: '2 || 3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  memorySize: 768
  timeout: 28
  environment:
    NODE_OPTIONS: --enable-source-maps
    API_GATEWAY_BASE_URL:
      Fn::Join:
        - ''
        - - 'https://'
          - Ref: HttpApi
          - '.execute-api.'
          - Ref: AWS::Region
          - '.amazonaws.com'
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            Fn::GetAtt:
              - CacheTable
              - Arn

plugins:
  - serverless-esbuild
  - serverless-local-schedule
  - serverless-s3-sync

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    plugins: esbuild-plugins.cjs
    packager: yarn
    exclude:
      - aws-sdk
      - chrome-aws-lambda
      - puppeteer-core
      - sharp
      - aws-sdk
  s3Sync:
    - bucketName: ${env:SERVICE_NAME}-assets
      localDir: assets
      acl: public-read

package:
  individually: true

layers:
  chromium:
    path: layers/chromium/build
  ffmpeg:
    path: layers/ffmpeg/build
  sharp:
    path: layers/sharp/build

functions:
  dabbext:
    handler: bots/dabbext/src/index.handler
    environment:
      BOT_TOKEN: ${env:DABBEXT_BOT_TOKEN}
    events:
      - httpApi:
          path: /bot${env:DABBEXT_BOT_TOKEN}
          method: post
  quote-generator:
    handler: bots/quote-generator/src/index.handler
    memorySize: 1536
    environment:
      ASSETS_BASE_URL: https://${env:SERVICE_NAME}-assets.s3.amazonaws.com
      RENDERER_PATH: /quote-generator/render
      BOT_TOKEN: ${env:QUOTE_GENERATOR_BOT_TOKEN}
      GCLOUD_PROJECT_ID: ${env:GCLOUD_PROJECT_ID}
      GCLOUD_CLIENT_EMAIL: ${env:QUOTE_GENERATOR_GCLOUD_CLIENT_EMAIL}
      GCLOUD_PRIVATE_KEY: ${env:QUOTE_GENERATOR_GCLOUD_PRIVATE_KEY}
      UNSPLASH_ACCESS_KEY: ${env:QUOTE_GENERATOR_UNSPLASH_ACCESS_KEY}
    events:
      - httpApi:
          path: /bot${env:QUOTE_GENERATOR_BOT_TOKEN}
          method: post
    layers:
      - { Ref: ChromiumLambdaLayer }
      - { Ref: FfmpegLambdaLayer }
    package:
      patterns:
        - 'bots/quote-generator/templates/**'
  quote-generator-renderer:
    handler: bots/quote-generator/src/renderer.handler
    memorySize: 1536
    environment:
      ASSETS_BASE_URL: https://${env:SERVICE_NAME}-assets.s3.amazonaws.com
    events:
      - httpApi:
          path: /quote-generator/render
          method: get
    layers:
      - { Ref: ChromiumLambdaLayer }
      - { Ref: SharpLambdaLayer }
  telegram-media-convert:
    handler: bots/telegram-media-convert/src/index.handler
    memorySize: 1536
    environment:
      ASSETS_BASE_URL: https://${env:SERVICE_NAME}-assets.s3.amazonaws.com
      BOT_TOKEN: ${env:TELEGRAM_MEDIA_CONVERT_BOT_TOKEN}
    events:
      - httpApi:
          path: /bot${env:TELEGRAM_MEDIA_CONVERT_BOT_TOKEN}
          method: post
    layers:
      - { Ref: FfmpegLambdaLayer }
      - { Ref: SharpLambdaLayer }
    package:
      patterns:
        - 'bots/telegram-media-convert/static/**'
  wotd:
    handler: bots/wotd/src/index.handler
    environment:
      BOT_TOKEN: ${env:WOTD_BOT_TOKEN}
      DYNAMODB_CACHE_TABLE: ${env:SERVICE_NAME}-cache
      CHAT_IDS_ALLOWLIST: ${env:WOTD_CHAT_IDS_ALLOWLIST}
      GOOGLE_CUSTOM_SEARCH_API_KEY: ${env:GOOGLE_CUSTOM_SEARCH_API_KEY}
      GOOGLE_CUSTOM_SEARCH_CX: ${env:GOOGLE_CUSTOM_SEARCH_CX}
    events:
      - schedule:
          rate: cron(1 18 * * ? *)
          timezone: Europe/Rome

resources:
  Resources:
    # The bucket used to store assets
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:SERVICE_NAME}-assets
        AccessControl: PublicRead
    # The cache table used by bots to store data that should persist across executions
    CacheTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:SERVICE_NAME}-cache
        AttributeDefinitions:
          - AttributeName: botToken
            AttributeType: S
          # NOTE: this is not needed, but it's added here for completeness
          # - AttributeName: val
          #   AttributeType: M
        KeySchema:
          - AttributeName: botToken
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
