org: dabolus
app: telegram-bots
service: telegram-bots
frameworkVersion: '2 || 3'
useDotenv: true
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    packager: yarn

package:
  individually: true

functions:
  dabbext:
    handler: bots/dabbext/src/index.handler
    environment:
      BOT_TOKEN: ${env:DABBEXT_BOT_TOKEN}
    events:
      - httpApi:
          path: /bot${env:DABBEXT_BOT_TOKEN}
          method: post
