org: dabolus
app: ${env:SERVICE_NAME}
service: ${env:SERVICE_NAME}
frameworkVersion: '2 || 3'
useDotenv: true
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-esbuild
  - serverless-s3-sync

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    packager: yarn
  s3Sync:
    - bucketName: ${env:SERVICE_NAME}-assets
      localDir: assets
      acl: public-read

package:
  individually: true

functions:
  dabbext:
    handler: bots/dabbext/src/index.handler
    environment:
      BOT_TOKEN: ${env:DABBEXT_BOT_TOKEN}
    events:
      - httpApi:
          path: /bot${env:DABBEXT_BOT_TOKEN}
          method: post

resources:
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:SERVICE_NAME}-assets
        AccessControl: PublicRead
